# Generated by Django 5.2.5 on 2025-10-06 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_blocked',
            field=models.BooleanField(default=False, help_text='Заблокирован ли пользователь', verbose_name='Заблокировать'),
        ),
    ]
