# Generated by Django 5.2.5 on 2025-10-06 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_is_blocked'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('can_block_user', 'Can block user'), ('can_view_users', 'Can view users')]},
        ),
    ]
