# Generated by Django 5.2.5 on 2025-09-22 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_flow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время окончания рассылки'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время начала рассылки'),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='comment',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Комментарий'),
        ),
    ]
