# Generated by Django 5.2.5 on 2025-09-30 21:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_flow', '0002_alter_mailing_end_time_alter_mailing_start_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mail_flow.message', verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Время начала рассылки'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mailingattempt',
            name='mailing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mail_flow.mailing', verbose_name='Письмо'),
        ),
        migrations.AlterField(
            model_name='mailingattempt',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время попытки рассылки'),
        ),
    ]
