# Generated by Django 5.2.5 on 2025-10-06 12:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_flow', '0004_mailing_owner_mailingattempt_owner_message_owner_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailingattempt',
            name='owner',
        ),
        migrations.AlterField(
            model_name='recipient',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterUniqueTogether(
            name='recipient',
            unique_together={('email', 'owner')},
        ),
    ]
