# Generated by Django 5.2.5 on 2025-10-06 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail_flow', '0005_remove_mailingattempt_owner_alter_recipient_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={'ordering': ['start_time', 'status'], 'permissions': [('can_view_mailings_list', 'Can view mailings list'), ('can_disable_mailing', 'Can disable mailing')], 'verbose_name': 'рассылка', 'verbose_name_plural': 'рассылки'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['subject'], 'permissions': [('can_view_messages_list', 'Can view messages list')], 'verbose_name': 'сообщение', 'verbose_name_plural': 'сообщения'},
        ),
    ]
