# Generated by Django 5.2.5 on 2025-10-06 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_flow', '0006_alter_mailing_options_alter_message_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активна'),
        ),
    ]
