# Generated by Django 5.2.5 on 2025-10-06 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail_flow', '0007_mailing_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipient',
            options={'ordering': ['full_name'], 'permissions': [('can_view_recipients_list', 'Can view recipients list')], 'verbose_name': 'получатель', 'verbose_name_plural': 'получатели'},
        ),
    ]
